name: Generate podcast feed
on: [push]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run Feed Generaor
        uses: ketankgupta/podcast-generator@main
        with:
          email: "${{ github.actor }}@localhost"
          name: "${{ github.actor }}"
